### ISSUE TITLE
(On Hyrax) Generator generates config file that doesn't work. Even generating the file, without changes, causes dashboard pages on collections to fail.

### ISSUE THREAD

**Issue by travisLilleberg** [samvera-labs/samvera-nesting_indexer#17]
I need to change the maximum nesting config option, but the generated config file causes the site to crash, at least on collection dashboard pages, when attempting to do so.

To Recreate (In a Hyrax site, specifically):

**1.** Create a collection in the Hyrax site.

**2.** Run the generator: `rails g samvera:nesting_indexer:install` - which creates the following file.
```
# rubocop:disable Style/FileName
require 'samvera/nesting_indexer'
# rubocop:enable Style/FileName

Samvera::NestingIndexer.configure do |config|
  # How many layers of nesting are allowed for collections
  # Given a maximum_nesting_depth of 3 the following will raise an exception:
  # C1 ={ C2 ={ C3 ={ C4
  # (e.g. C4 is a member of C3 is a member of C2 is a member of C1)
  config.maximum_nesting_depth = 5

  # The adapter that implements the Samvera::NestingIndexer::Adapter interface
  # config.adapter = Hyrax::Adapters::NestingIndexAdapter

  # The field names of the index layer attributes; These are not used by Samvera::NestingIndexer but
  # are certainly useful as part of implementing a Samvera::NestingIndexer::Adapter interface
  # config.solr_field_name_for_storing_parent_ids = Solrizer.solr_name('nesting_collection__parent_ids', :symbol)
  # config.solr_field_name_for_storing_ancestors =  Solrizer.solr_name('nesting_collection__ancestors', :symbol)
  # config.solr_field_name_for_storing_pathnames =  Solrizer.solr_name('nesting_collection__pathnames', :symbol)
  # config.solr_field_name_for_deepest_nested_depth =  Solrizer.solr_name('nesting_collection__deepest_nested_depth', :integer)
end
```

**3.** This immediately breaks the edit page of any collection. Just go to http://SITE/dashboard/collections/COLLECTION_ID and see the following error:
```
Expected :solr_field_name_for_storing_parent_ids to be set in Config #<Samvera::NestingIndexer::Configuration:0x00007fb0b59aeb48 
   @maximum_nesting_depth=5, 
   @logger=#<ActiveSupport::Logger:0x00007fb0b1cd5dc0 
      @level=0, 
      @progname=nil, 
      @default_formatter=#<Logger::Formatter:0x00007fb0b1cd5d48 
         @datetime_format=nil
      >, 
      @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x00007fb0ad4b4bb8 
         @datetime_format=nil, 
         @thread_key="activesupport_tagged_logging_tags:70198399182300"
      >, 
      @logdev=#<Logger::LogDevice:0x00007fb0b1cd5cf8 
         @shift_period_suffix=nil, 
         @shift_size=nil, 
         @shift_age=nil, 
         @filename=nil, 
         @dev=#<File:/Users/tlille01/Sites/trove/log/development.log>, 
         @mon_mutex=#<Thread::Mutex:0x00007fb0b1cd5b18
      >, 
      @mon_mutex_owner_object_id=70198436998780, 
      @mon_owner=nil, 
      @mon_count=0
   >, 
   @local_levels=#<Concurrent::Map:0x00007fb0b1cd59b0 
      entries=0 
      default_proc=nil
   >
>>
```

**4.** The obvious response to this, is to uncomment the solr field config settings inside the new config file. So I uncomment:
- config.solr_field_name_for_storing_parent_ids
- config.solr_field_name_for_storing_ancestors
- config.solr_field_name_for_storing_pathnames
- config.solr_field_name_for_deepest_nested_depth

After uncommenting those four settings, the site won't start at all, with the following error:
```
Traceback (most recent call last):
	63: from bin/rails:9:in `<main>'
	62: from bin/rails:9:in `require'
	61: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<top (required)>'
	60: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
	59: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
	58: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	57: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	56: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	55: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `perform'
	54: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `tap'
	53: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	52: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:42:in `start'
	51: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	50: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	49: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:24:in `app'
	48: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	47: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	46: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	45: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	44: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	43: from config.ru:in `<main>'
	42: from config.ru:in `new'
	41: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	40: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	39: from config.ru:3:in `block in <main>'
	38: from config.ru:3:in `require_relative'
	37: from /Users/tlille01/Sites/trove/config/environment.rb:5:in `<top (required)>'
	36: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/application.rb:353:in `initialize!'
	35: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/initializable.rb:58:in `run_initializers'
	34: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	33: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	32: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	31: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
	30: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
	29: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	28: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	27: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	26: from /Users/tlille01/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	25: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	24: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `run'
	23: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/initializable.rb:30:in `instance_exec'
	22: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/railties-5.1.6.2/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
	21: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/reloader.rb:87:in `prepare!'
	20: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:130:in `run_callbacks'
	19: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `invoke_before'
	18: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `each'
	17: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:507:in `block in invoke_before'
	16: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:198:in `block in halting'
	15: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:600:in `block in default_terminator'
	14: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:600:in `catch'
	13: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
	12: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
	11: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:413:in `block in make_lambda'
	10: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:413:in `instance_exec'
	 9: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer/railtie.rb:8:in `block in <class:Railtie>'
	 8: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer.rb:91:in `configure!'
	 7: from /Users/tlille01/Sites/trove/config/initializers/samvera-nesting_indexer_initializer.rb:20:in `block in <top (required)>'
	 6: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer.rb:35:in `solr_name'
	 5: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/caching_field_mapper.rb:13:in `solr_name'
	 4: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/caching_field_mapper.rb:22:in `cache'
	 3: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/caching_field_mapper.rb:14:in `block in solr_name'
	 2: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/field_mapper.rb:130:in `solr_name'
	 1: from /Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/field_mapper.rb:149:in `indexer'
/Users/tlille01/.rvm/gems/ruby-2.6.1@trove/gems/solrizer-4.1.0/lib/solrizer/field_mapper.rb:140:in `index_type_macro': Unable to find `integer' in [Solrizer::DefaultDescriptors] (Solrizer::UnknownIndexMacro)
```

At this point I figured I'd ask why these generated files don't seem to be working.

Thank you.

**Comment by travisLilleberg** [comment]
It was possibly an issue with both Hyrax and my app having a config for this? I dunno, but I copied hyrax's config and changed the number and it worked.
